{{- if and .Values.hetzner.token (not .Values.hetzner.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hcloud-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hcloud-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.hetzner.token | quote }}
{{- end }}
