{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hetzner-server-controller.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hetzner-server-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "hetzner-server-controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
{{- end }}
