{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hetzner-server-controller.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hetzner-server-controller.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    {{- include "hetzner-server-controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.metrics.port }}
      targetPort: http
      protocol: TCP
{{- end }}
