{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hcloud-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hcloud-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "hcloud-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
{{- end }}
